In [1]:
import pickle
import joblib
from sklearn.linear_model import  LinearRegression

c:\Users\Sadha\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\Sadha\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\Users\Sadha\anaconda3\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
import pandas as pd


In [9]:
df = pd.read_csv(r'C:\DS_Material\FastAPI_Material\venv\Model_serialization\housing.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [10]:
df = df.iloc[:,:-1].dropna()
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value  
0       322.0       126.0         8.3252            452600.0  
1      2401.0      1138.0         8.3014            358500.0  
2       496.0       177.0         7.2574            352100.0  
3       558.0       219.0         5.6431            341300.0  
4       565.0       259.0         3.8462            342200.0

In [12]:
X = df.drop(columns='median_house_value')
y = df.median_house_value

In [13]:
print(X.shape,y.shape)

(20433, 8) (20433,)


## Train the model

In [14]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [15]:
y_pred = model.predict(X)

In [16]:
y_pred

array([411270.20746022, 415943.95527541, 380534.16332106, ...,
        24989.18869284,  37961.51486099,  55555.76850637])

In [18]:
from sklearn.metrics import r2_score

In [19]:
r2_score(y,y_pred)

0.6369116857335635

## Pickle File

In [21]:
with open('model.pkl','wb') as f:
    pickle.dump(model,f)

In [22]:
with open('model.pkl','rb') as f:
    picket_model = pickle.load(f)

In [24]:
picket_model

LinearRegression()

In [26]:
y_pred_pickle = picket_model.predict(X)
y_pred_pickle

array([411270.20746022, 415943.95527541, 380534.16332106, ...,
        24989.18869284,  37961.51486099,  55555.76850637])

In [27]:
r2_score(y,y_pred_pickle)

0.6369116857335635

## Joblib

In [28]:
joblib.dump(model,'model.joblib')

['model.joblib']

In [30]:
joblib_model  = joblib.load('model.joblib')
joblib_model

LinearRegression()

In [31]:
y_pred_joblib = picket_model.predict(X)
y_pred_joblib

array([411270.20746022, 415943.95527541, 380534.16332106, ...,
        24989.18869284,  37961.51486099,  55555.76850637])

In [32]:
r2_score(y,y_pred_joblib)

0.6369116857335635